# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a0a8d933bab1fa9d8e0e48ac379d9d554af84c40d166084e848a95bd5d6160e43ead49c0c3cb6cc1140e3fb4c50947c9709cf6959d07d9e1b89fc636b43fbf7

test:
  secret_key_base: 00f37bc10a124d7b1af632000042af321bc401fee879fc2af1e27c3b59c627183cdf902b86959acc510d9051bb19b7a6507571fb1a9b12574967e3eb6d2a51e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
